Add fixLegacyNum to export list
The function 'fixLegacyNum' is used by the test
suite, so it needs to be exported.

Fixes the following error:

> Variable not in scope:
>   fixLegacyNum